### ISSUE TITLE
Feature: User can view random wallpapers

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/previous-ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view random wallpapers
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user

When a user clicks the random button, random wallpapers will be shown

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-06-08 at 5 08 12 PM](https://user-images.githubusercontent.com/82190583/121273028-29ef9880-c87c-11eb-9061-515a8f78acad.png)
![Screen Shot 2021-06-08 at 5 08 58 PM](https://user-images.githubusercontent.com/82190583/121273065-3aa00e80-c87c-11eb-8c16-a73d0d113148.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create an html skeleton with tags and add CSS to the page.
- [x] work on web responsiveness of the desktop version. 
- [x] create an anchor tag that will be used as the random link. 
- [x] send an HTTP request to get data for the wallpapers. 
- [x] add a 'click' event to the random link 

- [x] create a DOM tree that will have wallpapers showing inside the body.
- [x] set it up to have three wallpapers on mobile and 9 wallpapers on desktop
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
