### ISSUE TITLE
Feature: User can search for a wallpaper with a search term

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/previous-ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

They can search for wallpapers of their choice by entering a term in the search bar. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user can click into the search bar and look up a term they want that could potentially have wallpapers associated with it. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-06-10 at 11 49 42 AM](https://user-images.githubusercontent.com/82190583/121580774-fc246400-c9e1-11eb-845e-50d6b7128e62.png)
![Screen Shot 2021-06-10 at 11 53 26 AM](https://user-images.githubusercontent.com/82190583/121581248-7a810600-c9e2-11eb-80e6-ad5ee4c367b1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a form inside the header. 
- [x] add a search bar to the header.
- [x] add a search button next to the header
- [x] create a function that sends a GET request for the terms to be searched
- [x] create a submit handler to call the function. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
