### ISSUE TITLE
Feature: User can search by color

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/previous-ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Now there's even more choices because users will be able to sort by color of the wallpaper as well. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user can choose a color by clicking the color input and searching for wallpapers that way. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-06-11 at 11 39 17 AM](https://user-images.githubusercontent.com/82190583/121734472-aadfa780-caa9-11eb-8853-390e00a70a59.png)
![Screen Shot 2021-06-11 at 11 39 51 AM](https://user-images.githubusercontent.com/82190583/121734526-bfbc3b00-caa9-11eb-80dd-65e63cb8abc7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a color input to the HTML next to the search bar
- [x] create a function that sends a GET request for the color selected and populates wallpapers base off that color.
- [x] create a new submit handler for the color function. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
