### ISSUE TITLE
Feature: User can save their favorite wallpapers

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/previous-ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save their favorite wallpapers

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user either searches for a wallpaper or clicks random they can save a wallpaper to their favorites album. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-06-15 at 12 48 48 PM](https://user-images.githubusercontent.com/82190583/122114368-0b3b5580-cdd8-11eb-8186-936476e346d5.png)
![Screen Shot 2021-06-15 at 12 49 38 PM](https://user-images.githubusercontent.com/82190583/122114463-27d78d80-cdd8-11eb-9de8-f4ce88f50c4c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a save button and append it to each image inside the DOM tree
- [x] Add an album icon and link 
- [x] create a new container to hold the favorited wallpapers. 
- [x] set up local storage to save the wallpapers into the album.
- [x] hide the search form container when we click the album container and vice-versa.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
